os:
  - linux
  - osx
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
before_script:
  - npm install winston@2.3.0
  - npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
